# This workflow will take the contents of the content branches and build a documentation site

name: Build site

on:
  push:
    branches: [ latest, latest-dev, archive ]

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['Actions-tester-jake/docs-poc']
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ff5c9cab70adf17afcffeda
